### ISSUE TITLE
lykj-vip: 切换数据，显隐滚动条，会左右抖动，希望有滚动条不占位的功能

### ISSUE THREAD

**Issue by web-ning** [surely-vue/surely-table#226]
![C1SE88PE0SF5Z98 YJA55VG](https://github.com/surely-vue/surely-table/assets/43629659/88bb304d-ae35-47b5-9b11-f4a8ab907026)
![WJR)V}F@R_9UR65R(XR7K97](https://github.com/surely-vue/surely-table/assets/43629659/d2b34dd6-38dc-4685-839e-cfc18a78a5b5)

**Comment by tangjinzhou** [comment]
什么叫滚动条不占位？ 直接盖上去，遮住其它元素 ？

**Comment by web-ning** [comment]
是的，项目里一般都会留有空余空间，类似el-scrollbar
![image](https://github.com/surely-vue/surely-table/assets/43629659/fac68a16-f7cb-4b58-98f8-0754744b2389)
![image](https://github.com/surely-vue/surely-table/assets/43629659/902df48a-0961-41c5-a9e7-52e0324135ab)

**Comment by tangjinzhou** [comment]
```css
.surely-table-header-scrollbar {
   display: none;
}
.surely-table-vertical-scroll {
   position: absolute;
   right:0;
}
```
