### ISSUE TITLE
请问该如何显示单元格内的滚动条？

### ISSUE THREAD

**Issue by qidai77777** [surely-vue/surely-table#233]
如果不想要单元格的选中样式应该写什么属性？  这些文档里面都没有写

![image](https://github.com/surely-vue/surely-table/assets/43577925/c38910e9-b785-4b07-b13b-b8370186cc82)

**Comment by tangjinzhou** [comment]
```css
.surely-table-cell-inner {
 overflow-y: auto;
}
```
请注意，改动会影响自动行高
