### ISSUE TITLE
配置bordered为true当有横向滚动条时，边框有缺失

### ISSUE THREAD

**Issue by clikli** [surely-vue/surely-table#263]
![image](https://github.com/user-attachments/assets/77c8cc5c-e5a0-459b-897c-55ee0e68ab23)

我自己的解决方案：
```css
.surely-table-bordered .surely-table-horizontal-scroll {
    border-right: 1px solid var(--surely-table-border-color);
}
```
